/*
Data Set pour peupler la base de données avec les données sur les épices.
Codé par Dorian Lecomte
*/
INSERT INTO `spice` (`spiceId`,`name`,`description`,`bareCode`) VALUES (1,'Muscade','La noix de muscade est utilisée râpée comme épice pour aromatiser les viandes, soupes, béchamels, gratins, assaisonner purées et plats à base de pommes de terre en général, légumes et même certains cocktails. Elle entre dans la composition de nombreux mélanges d’épices tel que le Curry, le quatre épices, ou encore le raz el hanout et le colombo. En cuisine française, elle est notamment employée pour aromatiser le gratin dauphinois. Le goût de la muscade est assez fort mais non piquant. Le plus souvent, une pincée suffira. Si vous aimez cette épice, nous vous conseillons de tester le macis, qui est l\'écorce de la muscade, possédant un goût très similaire mais en poivré, citronné et beaucoup plus fin. Si vous n\'avez plus de muscade ni de macis, vous pourrez employer les fèves tonka à la place, leur goût est différent mais dans le salé, elles s\'utilisent de la même manière que les deux épices. ','4a0012ee04');

INSERT INTO `spice` (`spiceId`,`name`,`description`,`bareCode`) VALUES (2,'Paprika','Le paprika est une épice en poudre de couleur rouge obtenu à partir du fruit mûr, séché et moulu du piment doux ou poivron. L\'épice est utilisée en cuisine pour son parfum âcre et sa couleur rouge. Son piquant est très doux et vous permet d’agrémenter vos plats d\'une touche parfumée et légèrement épicée. Les Hongrois l\'emploient en grande quantité que ce soit dans leurs goulaschs, leurs ragoûts ou encore leurs plats de volaille. Il se mariera parfaitement à vos ragoûts de viande et de volaille, dans les fromages frais, la crème, le poisson, la tomate, les oignons ou encore l’avocat. Le paprika est sucré, ne le faites pas trop cuire sinon il prendra un goût amer. ','4a0012fa94');

INSERT INTO `spice` (`spiceId`,`name`,`description`,`bareCode`) VALUES (3,'Piment','Le piment entre dans de nombreux plats typiques du Pays Basque, par exemple : le Marmitako, la Piperade à l\'Ibaïona, l\'Axoa d\'Espelette, etc. C’est un piment très parfumé dont l\'usage s’étend à tous les plats. Excellent dans la ratatouille et tous les plats de tomates (crues ou cuites). Utilisez-le dans toutes les viandes, que ce soient les viandes blanches, le lapin, la viande de mouton, bœuf, etc. Une pincée en fin de cuisson suffira à aromatiser votre viande. Vous pouvez l\'employer dans le porc et la charcuterie de manière générale. En accompagnement, il parfumera à merveille vos pâtes, riz et plats de pomme de terre. Il assaisonnera parfaitement vos œufs dans toutes leurs variantes. Il parfume les sauces, particulièrement aux produits laitiers tels que le yaourt nature, le lait de coco, le fromage blanc ou la crème fraîche. Dans le pays Basque, on confectionne la mayonnaise en remplaçant la moutarde par du piment d’Espelette. Il est aussi parfait pour épicer les poissons de toutes sortes, mais son mariage avec le brochet et la raie est particulièrement délicieux. Avec un piquant équivalant au poivre, vous pouvez l’intégrer dans vos salades de toutes sortes. Plus étonnant mais tout aussi bon, vous pouvez l’intégrer (une pincée) dans vos desserts, surtout les desserts à base de chocolat. Pour profiter au maximum de sa saveur, rajoutez-le en fin de cuisson ou même après la cuisson.','5c005c8aeb');

INSERT INTO `spice` (`spiceId`,`name`,`description`,`bareCode`) VALUES (4,'Poivre','Le poivre est une épice obtenue à partir des baies de différentes espèces de poivriers. Seuls ont droit à l\'appellation de « poivre » les fruits du poivrier noir qui donnent le poivre vert, blanc, rouge ou noir. Par analogie, d\'autres épices qui proviennent de plantes bien différentes reprennent ce nom, mais ces faux poivres ont d\'autres caractéristiques botaniques et donnent des saveurs différentes. Le poivre noir est l’une des épices les plus employées dans le monde. C’est le plus piquant et le plus aromatique des poivres. On l’ajoute pratiquement à tous les aliments et toutes les recettes : potages, viandes, légumes, vinaigrettes, sauces, etc. On rajoute toujours le poivre en fin de cuisson, une pincée suffit à relever subtilement un plat. Un usage plus surprenant consiste à l\'utiliser pour aromatiser des thés et des infusions.','5c005cb6b9');

INSERT INTO `spice` (`spiceId`,`name`,`description`,`bareCode`) VALUES (5,'Réglisse','Le réglisse sert principalement à donner du goût dans les pâtisseries et les boissons. Sa racine peut aussi se déguster tel quel en bouche, à l\'image d\'une friandise. En Asie, on l\'utilise pour adoucir les soupes et dans certains mélanges d’épices. Le réglisse est excellent saupoudré sur du poulet. Son usage est très répandu dans la cuisine thaïlandaise. Vous pouvez vous en servir pour aromatiser vos thés et infusions.','5c005cc39b');

INSERT INTO `spice` (`spiceId`,`name`,`description`,`bareCode`) VALUES (6,'Vanille','Coupez dans le sens de la longueur votre gousse afin d\'en extraire les graines. Vous n\'êtes pas obligé de l\'ouvrir sur toute sa longueur, quelques centimètres suffiront, vous pourrez ainsi la réutiliser à plusieurs reprises ! Séparez la gousse en 2 et raclez l\'intérieur de cette demi-gousse à l\'aide de la lame de votre couteau pour en extraire les graines. Les graines ainsi obtenues se mélangeront maintenant parfaitement à votre préparation. On peut récupérer les 2 demi-gousses vidées, soit pour parfumer votre bocal de sucre, soit pour les incorporer dans vos recettes mais en principe elles ne se mangent pas. Laissez chauffer les graines et le reste de la gousse une dizaine de minutes dans le lait sans porter à ébullition. Plus les graines resteront longtemps, plus la saveur sera bien imprégnée. La vanille sublime tous les desserts mais vous pouvez aussi vous en servir pour parfumer vos thés et infusions. Enfin, elle se marie très bien aux viandes blanches ainsi qu’aux préparations au lait de coco.','5c005ce795');
